-- AlterTable
ALTER TABLE `internship` ADD COLUMN `aboutInternship` VARCHAR(191) NULL,
    ADD COLUMN `certificate` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `companyName` VARCHAR(191) NULL,
    ADD COLUMN `educationLevel` VARCHAR(191) NULL,
    ADD COLUMN `experienceRequired` VARCHAR(191) NULL,
    ADD COLUMN `hoursPerDay` INTEGER NULL,
    ADD COLUMN `jobOffer` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `locationType` VARCHAR(191) NULL,
    ADD COLUMN `numberOfOpenings` INTEGER NULL,
    ADD COLUMN `otherBenefits` VARCHAR(191) NULL,
    ADD COLUMN `requiredSkills` VARCHAR(191) NULL,
    ADD COLUMN `rolesResponsibilities` VARCHAR(191) NULL,
    ADD COLUMN `selectionProcess` VARCHAR(191) NULL,
    ADD COLUMN `startDate` DATETIME(3) NULL,
    ADD COLUMN `type` VARCHAR(191) NULL,
    ADD COLUMN `whatInternWillLearn` VARCHAR(191) NULL,
    ADD COLUMN `workingHours` VARCHAR(191) NULL,
    MODIFY `status` VARCHAR(191) NOT NULL DEFAULT 'OPEN';
